ValueOfObjects_HW сделал!
scorpdubovik/Lesson_6 pull request #10
Opened 2022-01-16 21:07 UTC by scorpdubovik

2022-01-17 10:43 UTC, wildpioneer requested changes

2022-01-17 10:43 UTC, wildpioneer commented on src/main/java/com/tms/core/ReadProperties.java
> +    public static String getProjectName2() {
У проекта только ОДНО имя

2022-01-17 10:43 UTC, wildpioneer commented on src/main/java/com/tms/core/ReadProperties.java
> +    public static String getRadioButton1() {
Мне ее понятно название свойства объекта RadioButton - Тип проекта подойдёт больше

2022-01-17 10:43 UTC, wildpioneer commented on src/test/java/models/Project.java
> +        String projectName =projectNames.get(random.nextInt(3));
Не совсем понимаю - это рандомизация?

2022-01-17 10:43 UTC, wildpioneer commented on src/test/java/pages/AddProjectPage.java
> +    public WebElement getRadioButton1() {return driver.findElement(radioButton1_Selector);}
Название переменной не говорящее

2022-01-17 10:43 UTC, wildpioneer commented on src/test/java/tests/HwSmokeTest.java
> +    public void updateProjectTest() {
Ошибка при выполнении:
org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//*[.= 'NewProject2']"}

2022-01-20 19:01 UTC, scorpdubovik commented on src/main/java/com/tms/core/ReadProperties.java
> +    public static String getProjectName2() {
Я просто задание изначально не правильно понял, думал что рандом должен выбирать из нескольких уже ранее заготовленных имен. В исправленном проекте в ReadProperties не будет getProjectName

2022-01-20 19:02 UTC, scorpdubovik commented on src/main/java/com/tms/core/ReadProperties.java
> +    public static String getRadioButton1() {
Да, согласен. Учту

2022-01-20 19:07 UTC, scorpdubovik commented on src/test/java/models/Project.java
> +        String projectName =projectNames.get(random.nextInt(3));
Как я понял в дз нам нужно было заиспользовать коллекцию. Сначала создается коллекция из ранее заготовленных имен. А потом рандомно вытягивается из коллекции по индексу любое имя. Конечно получилось примитивно, как я понимаю так совсем плохо ? Но я переделаю с отдельным классом Randomization и сделаю класс Enum

2022-01-20 19:13 UTC, scorpdubovik commented on src/test/java/pages/AddProjectPage.java
> +    public WebElement getRadioButton1() {return driver.findElement(radioButton1_Selector);}
Ok, исправлю

2022-01-20 19:32 UTC, scorpdubovik commented on src/test/java/tests/HwSmokeTest.java
> +    public void updateProjectTest() {
Похоже когда создается новый проект в тесте addNewProjectTest в нем я инициализирую объект Project, который генерит одно из 3х имен проекта. А когда выполняется тест updateProjectTest в нем также я объявляю объект Project который может сгенерировать уже другое имя и тогда не срабатывает селектор findElement(By.xpath("//*[.= '"+project.getProjectName()+"']")). И этот тест у меня срабатывает наверняка когда уже есть 3 созданных проекта со всеми возможными именами. Нужно как то было сохранить в переменной изначально сгенерированное имя проекта, но у меня не получилось( .

2022-01-31 11:29 UTC, wildpioneer commented
Проверено

2022-01-31 11:29 UTC, closed without merging